### ISSUE TITLE
[Other]: React Native version issue

### ISSUE THREAD

**Issue by HenryWu01** [openimsdk/open-im-sdk-reactnative#10]
### What would you like to share?

我在 npmjs 网站看到目前 OpenIM React Native 的版本是 ``3.4.2``，但是目前项目储存库中的 package.json 版本是 ``3.4.0``，Tag 和 Release 只有一个不存在的版本 ``1.0.7``，请问是否会更新一下提交、Tag 和 Release？

**Comment by AndrewZuo01** [comment]
之后会的

**Comment by HenryWu01** [comment]
> 之后会的

感谢回复~收到
