### ISSUE TITLE
initSDK failed

### ISSUE THREAD

**Issue by OrrinHatch** [openimsdk/open-im-sdk-reactnative#22]
### OpenIM Server Version

3.7.1

### Operating System and CPU Architecture

macOS (ARM)

### Deployment Method

Source Code Deployment

### Bug Description and Steps to Reproduce

<img width="1074" alt="截屏2024-08-07 17 18 32" src="https://github.com/user-attachments/assets/e0e14f3f-8cd4-4036-8a6e-ccf4d5006ddc">
日志:  initSDK error [Error: please check params and dir]

**Comment by OrrinHatch** [comment]
help me, thanks

**Comment by OrrinHatch** [comment]
` "open-im-sdk-rn": "^3.5.1-rc.2",`

**Comment by OrrinHatch** [comment]
<img width="1032" alt="截屏2024-08-07 17 26 19" src="https://github.com/user-attachments/assets/ebf61f8b-7085-42b4-854c-d67bf7f42781">
这里也确认没问题

**Comment by OrrinHatch** [comment]
`export const initSDK = async function () {
    await RNFS.mkdir(`${RNFS.DocumentDirectoryPath}/tmp`);

    console.log(`initSDK params:${JSON.stringify({
      platformID: platformID,
      apiAddr: getApiUrl(),
      wsAddr: getWsUrl(),
      dataDir: `${RNFS.DocumentDirectoryPath}/tmp`,
      logLevel: 5,
      isLogStandardOutput: true,
    })}, uuid: ${uuidv4()}`);

    OpenIMSDKRN.initSDK(
      {
        platformID: platformID,
        apiAddr: getApiUrl(),
        wsAddr: getWsUrl(),
        dataDir: `${RNFS.DocumentDirectoryPath}/tmp`,
        logLevel: 5,
        isLogStandardOutput: true,
      },
      uuidv4(),
    )
      .then(() => {
        console.log(`initSDK success, platformID: ${platformID}, platform OS: ${Platform.OS}`);
      })
      .catch((error) => {
        console.log('initSDK error', error);
      });
};` 这是我按照官方文档的建议去写,还是报错

**Comment by Bloomingg** [comment]
Can you print the parameters passed in?

**Comment by OrrinHatch** [comment]
```
{"platformID":2,"apiAddr":"http://ip:10002","wsAddr":"ws://ip:10001","dataDir":"/data/user/0/com.sass_crm_rn_cn/files/tmp","logLevel":5,"isLogStandardOutput":true}
uuid: 9b682e5d-5ae8-4eed-bc3e-140ab3d5b013
```

**Comment by Bloomingg** [comment]
It seems to be correct. You can connect to the logcat of android studio to check Golog.

**Comment by OrrinHatch** [comment]
> It seems to be correct. You can connect to the logcat of android studio to check Golog.

![Uploading 截屏2024-08-07 23.04.25.png…]()

**Comment by Bloomingg** [comment]
What is your react-native version?

**Comment by OrrinHatch** [comment]
> 你的react-native版本是多少？ 好像是在native层解析NativeMap的时候出错了，低版本可能会出现这种情况。

**Comment by OrrinHatch** [comment]
> > 你的react-native版本是多少？好像是在native层解析NativeMap的时候出错了，低版本可能会出现这种情况。  
"react-native": "^0.70.14",

**Comment by OrrinHatch** [comment]
"react-native": "^0.70.14",

**Comment by OrrinHatch** [comment]
`I am using JD Taro framework, and upgrading React Native versions is very cumbersome.`

**Comment by OrrinHatch** [comment]
```
  private String readableMap2string(ReadableMap map) {
    return map.toString();
  }
  This code returns different results in different versions of react-native.
```

**Comment by OrrinHatch** [comment]
Solution:
```
 private static String readableMap2string(ReadableMap map) {
        try {
            // 将 ReadableMap 转换为 HashMap
            HashMap<String, Object> hashMap = map.toHashMap();

            // 使用 fastjson 将 HashMap 转换为 JSON 字符串
            return JSON.toJSONString(hashMap);
        } catch (Exception e) {
            e.printStackTrace();
            return "{}";  // 如果发生错误，返回一个空的 JSON 对象
        }
    }
```
