### ISSUE TITLE
open-im-sdk-rn initSDK failed

### ISSUE THREAD

**Issue by OrrinHatch** [openimsdk/open-im-sdk-reactnative#24]
### OpenIM Server Version

3.7.1

### Operating System and CPU Architecture

macOS (ARM)

### Deployment Method

Source Code Deployment

### Bug Description and Steps to Reproduce

<img width="1074" alt="截屏2024-08-07 17 18 32" src="https://github.com/user-attachments/assets/28d85860-debf-4252-9dbf-796f9ad2e44c">
参数和目录都没问题 initSDK error [Error: please check params and dir]

**Comment by Bloomingg** [comment]
#22

**Comment by lgz5689** [comment]
sdk updated to the latest 3.8.1-rc.0
