### ISSUE TITLE
OpenIMSDKRN.login the application has crashed.

### ISSUE THREAD

**Issue by OrrinHatch** [openimsdk/open-im-sdk-reactnative#27]
### OpenIM Server Version

3.7.1

### Operating System and CPU Architecture

macOS (ARM)

### Deployment Method

Source Code Deployment

### Bug Description and Steps to Reproduce

执行登录操作后,程序程序崩溃

**Comment by lgz5689** [comment]
![image](https://github.com/user-attachments/assets/ffc50531-8b83-4414-a970-7704a6fa6609)
use latest version

**Comment by OrrinHatch** [comment]
solved, thanks
