### ISSUE TITLE
[BUG] OpenIMSDKRN.sendMessage fail

### ISSUE THREAD

**Issue by OrrinHatch** [openimsdk/open-im-sdk-reactnative#30]
### OpenIM Server Version

3.8.0

### Operating System and CPU Architecture

macOS (ARM)

### Deployment Method

Docker Deployment

### Bug Description and Steps to Reproduce

```
const options = {"groupID": "", "message": {"clientMsgID": "8711d448b1d7c519f0040ff78d7e7fb0", "contentType": 101, "createTime": 1723458869536, "isRead": false, "msgFrom": 100, "sendID": "6111529997", "sendTime": 1723458869536, "senderNickname": "curry", "senderPlatformID": 2, "seq": 0, "sessionType": 0, "status": 1, "textElem": {"content": "SD"}}, "recvID": "2004242507"}

try {
   const successMessage = await OpenIMSDKRN.sendMessage(options, uuidv4());
} catch(error) {
   console.log('发送消息失败:', error); // 发送消息失败:  Error: json: cannot unmarshal number 1.723458869536E12 into Go struct field MsgStruct.createTime of type int64
}
```

**Comment by Bloomingg** [comment]
Did you create the message via createTextMessage?
Note: Do not construct the message body yourself

**Comment by OrrinHatch** [comment]
use  const message = await OpenIMSDKRN.createTextMessage(text, uuidv4());

Based on the error message, it appears that the createTime field is being parsed as an int64 type in Go, while the number in the JSON is being interpreted in scientific notation (e.g., 1.723458869536E12), leading to a parsing failure.

**Comment by OrrinHatch** [comment]
I submit a PR

**Comment by OrrinHatch** [comment]
```
import com.alibaba.fastjson.serializer.SerializerFeature;

private String readableMap2string(ReadableMap map) {
    try {
      HashMap<String, Object> hashMap = map.toHashMap();
      return JSON.toJSONString(hashMap, SerializerFeature.WriteNonStringValueAsString);
    } catch (Exception e) {
        e.printStackTrace();
        return "{}";
    }
  }
```
use of SerializerFeature.WriteNonStringValueAsString will only convert Number types (such as int, long, float, double) to strings.

**Comment by lgz5689** [comment]
There are many other methods that also use `map.toString()` and you need to determine if you want to replace them all with `readableMap2string`

**Comment by lgz5689** [comment]
updated to the latest 3.8.1-rc.0

**Comment by lgz5689** [comment]
updated to the latest 3.8.1-rc.1

**Comment by lgz5689** [comment]
> updated to the latest 3.8.1-rc.1

You are recommended to refer to the lower version https://github.com/openimsdk/open-im-sdk-reactnative/issues/32
