### ISSUE TITLE
[BUG] xxx is not supported event type for OpenIMSDKRN

### ISSUE THREAD

**Issue by 15975019972** [openimsdk/open-im-sdk-reactnative#31]
### OpenIM Server Version

3.7.1

### Operating System and CPU Architecture

macOS (ARM)

### Deployment Method

Source Code Deployment

### Bug Description and Steps to Reproduce

![image](https://github.com/user-attachments/assets/0fb0ea3f-5cc5-4a30-a2e7-c05c75674777)
在测试聊天界面的时候发现没有实时收到消息

**Comment by Bloomingg** [comment]
we will fix next version
