### ISSUE TITLE
[BUG] createImageMessageFromFullPath return empty

### ISSUE THREAD

**Issue by neilzhengzx** [openimsdk/open-im-sdk-reactnative#34]
### OpenIM Server Version

open-im-sdk-rn  3.5.1-rc.2

### Operating System and CPU Architecture

macOS (ARM)

### Deployment Method

Source Code Deployment

### Bug Description and Steps to Reproduce

[new demo release](https://github.com/openimsdk/openim-reactnative-demo/commit/eb02ddff3466e9e202c41623dfe99dd9379b592b) 
String message = Open_im_sdk.createImageMessageFromFullPath(operationID, imagePath); 
message get ""

**Comment by lgz5689** [comment]
see https://github.com/openimsdk/open-im-sdk-reactnative/issues/32

**Comment by lgz5689** [comment]
> see #32

You are recommended to refer to the lower version https://github.com/openimsdk/open-im-sdk-reactnative/issues/32

**Comment by c2pc** [comment]
> см [. №32](https://github.com/openimsdk/open-im-sdk-reactnative/issues/32)

0.72.6

**Comment by c2pc** [comment]
> > `"open-im-sdk-rn": "3.8.1-rc.0"`
> > Код `OpenIMSDKRN.createFileMessageFromFullPath({ filePath:uri, fileName: name }, Date.now().toString())`возвращает ошибку **Значение для сообщения не может быть преобразовано из String в ReadableNativeMap**
> > но если я отправляю String, код `OpenIMSDKRN.createFileMessageFromFullPath(uri, Date.now().toString())`также возвращает ошибку **String не может быть приведен к ReadableNativeMap**
> > В OpenImSdkRnModule.java я вижу, `public void createFileMessageFromFullPath(ReadableMap options, String operationID, Promise promise)`но в файле JS `createFileMessageFromFullPath: ( params: string, operationID: string ) => Promise<MessageItem>;`параметры — это строка
> 
> Какова ваша версия?`react-native`

0.72.6

**Comment by c2pc** [comment]
> see #32

I updated the version to the latest, corrected the java file, but my error is the same
**Value for message cannot be cast from String to ReadableNativeMap** in **OpenIMSDKRN.createFileMessageFromFullPath({ filePath:uri, fileName: name }, Date.now().toString())**

but it works in iOS

react-native: 0.72.6
open-im-sdk-reactnative: 3.8.1-rc.1

**Comment by lgz5689** [comment]
> > see #32
> 
> I updated the version to the latest, corrected the java file, but my error is the same **Value for message cannot be cast from String to ReadableNativeMap** in **OpenIMSDKRN.createFileMessageFromFullPath({ filePath:uri, fileName: name }, Date.now().toString())**
> 
> but it works in iOS
> 
> react-native: 0.72.6 open-im-sdk-reactnative: 3.8.1-rc.1

Please read this article carefully. Obviously you didn't read it in its entirety

**Comment by daxingyun** [comment]
您好，创建文件和视频消息时，返回空值，创建图片消息正常。
截图如下：
![微信图片_20240927155151](https://github.com/user-attachments/assets/dc45b8eb-037c-4300-9303-281259a7cc7a)
![微信图片_20240927155243](https://github.com/user-attachments/assets/16f7e1f2-d114-4d2a-a7d3-019b6b526699)

请注意看打印的日志，我有输出filePath的值 以及返回的message。
日志可以看出message是返回空值。  

异常信息为：[open_im_sdk/caller.go:260]                       	fn call error

除此之外没有任何别的有用信息。

**Comment by lgz5689** [comment]
> 您好，创建文件和视频消息时，返回空值，创建图片消息正常。 截图如下： ![微信图片_20240927155151](https://private-user-images.githubusercontent.com/18024966/371444122-dc45b8eb-037c-4300-9303-281259a7cc7a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAzNTY0MzQsIm5iZiI6MTczMDM1NjEzNCwicGF0aCI6Ii8xODAyNDk2Ni8zNzE0NDQxMjItZGM0NWI4ZWItMDM3Yy00MzAwLTkzMDMtMjgxMjU5YTdjYzdhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDMxVDA2Mjg1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM1ZjMwMzdkOTU3NmJkMTY2OTZiZmVmN2FmYzMyNjg2ZmZlNTQ0Mzk4MDY1ODBkNjc3ZDVhN2FkNDcxMjdlZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.fxl142AMmdByTGqXoXXdAujZjWlNFLzfw5cotapRBv0) ![微信图片_20240927155243](https://private-user-images.githubusercontent.com/18024966/371444134-16f7e1f2-d114-4d2a-a7d3-019b6b526699.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAzNTY0MzQsIm5iZiI6MTczMDM1NjEzNCwicGF0aCI6Ii8xODAyNDk2Ni8zNzE0NDQxMzQtMTZmN2UxZjItZDExNC00ZDJhLWE3ZDMtMDE5YjZiNTI2Njk5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDMxVDA2Mjg1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ2ZDA2NDAxM2Q4MDE0YWI2OTRlMWE1NDg3OWMzZTk5N2I3NTNkOWM2YTE3YjQ3M2RmNTY3Y2I2M2UyMzZkNDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.gZ0WMGrM55MOP7qmMlCi1XDWcnpK3q3BFXGoe5Xzxww)
> 
> 请注意看打印的日志，我有输出filePath的值 以及返回的message。 日志可以看出message是返回空值。
> 
> 异常信息为：[open_im_sdk/caller.go:260] fn call error
> 
> 除此之外没有任何别的有用信息。

Collect more logs in the console, only one `fn call error` can not troubleshoot the problem, you need to provide more logs to find the problem

**Comment by Rater93** [comment]
聊天传图片的场景，我用createImageMessageFromFullPath
运行环境：ios模拟器，react native版本3.8.1，服务端版本release-v3.8.1

console.info('messageItem::', mediaPath, operationID)
messageItem = await OpenIMSDKRN.createImageMessageFromFullPath(mediaPath, operationID);
console.info('messageItem::', messageItem)

结果messageItem 返回空，

![632f08fe8875fa9172e4cbd112d1b02](https://github.com/user-attachments/assets/5a6cac17-5104-4ecc-b06e-a2f6d08c83bf)

**Comment by lgz5689** [comment]
Try to remove `file://`, and confirm that the app permission has been applied, if it has not been properly executed, please provide more sdk-core log content

**Comment by Rater93** [comment]
> Try to remove `file://`, and confirm that the app permission has been applied, if it has not been properly executed, please provide more sdk-core log content尝试去掉`file://` ，并确认app权限已经申请，如果没有正确执行，请提供更多sdk-core日志内容


去掉file后，还是有问题
messageItem:: {"clientMsgID": "6701b6586d52cdcc96dfbdebd25abb19", "contentType": 102, "createTime": 1730382771646, "isRead": false, "msgFrom": 100, "pictureElem": {"sourcePath": "/Users/vikiy/Library/Developer/CoreSimulator/Devices/A2AFC8A2-9B87-4F6E-8FE6-13C3C47DA414/data/Containers/Data/Application/2C31320F-CF27-4C0B-85BE-35DA2C85C1C2/tmp/8AA2A516-BF3C-4A21-A345-4EC29677833E.jpg", "sourcePicture": {"height": 2500, "size": 0, "type": "image/jpeg", "width": 1668}}, "sendID": "6610e5056afc8c5cb2fb970c", "sendTime": 1730382771646, "senderFaceUrl": "https://joyn-user-avatar.s3.us-west-2.amazonaws.com/file.d07f847e0550431da3f8e2a48fead2b8_avatar.jpg", "senderNickname": "AmyJohnsson", "senderPlatformID": 1, "seq": 0, "sessionType": 0, "status": 1}

sourcePicture并没有url等信息，size也是为0，height,width倒是有

**Comment by lgz5689** [comment]
This is normal, and when the message is successfully sent, the callback returns a message body containing all the contents

**Comment by Rater93** [comment]
> This is normal, and when the message is successfully sent, the callback returns a message body containing all the contents这是正常的，当消息发送成功后，回调会返回包含所有内容的消息体

消息内容只有IOS虚拟机的路径，对于消息接收方来说，这个路径有什么意义么，没有其他可用的可用于展示这个图片的消息内容吗

**Comment by lgz5689** [comment]
After the message has been successfully sent, you can get the complete structure of the message.  The `sourcePath `doesn't make sense to the message receiver.

**Comment by lgz5689** [comment]
Check the console `sendMessage` for errors, then collect local *sdk-core* logs.
