### ISSUE TITLE
[BUG] To delete a user's relationship chain in an IM system, how can I monitor when that user's friends are deleted?

### ISSUE THREAD

**Issue by OrrinHatch** [openimsdk/open-im-sdk-reactnative#35]
### OpenIM Server Version

3.8.0

### Operating System and CPU Architecture

macOS (ARM)

### Deployment Method

Docker Deployment

### Bug Description and Steps to Reproduce

To delete a user's relationship chain in an IM system, how can I monitor when that user's friends are deleted?

**Comment by Bloomingg** [comment]
The friend relationship is one-way. The main function of the OnFriendDeleted callback is to synchronize multiple terminals when you delete a friend. It cannot detect that the other party has deleted your friend.

**Comment by OrrinHatch** [comment]
thanks
