### ISSUE TITLE
[BUG] OpenIMSDKRN.login will cause app crash

### ISSUE THREAD

**Issue by ahjsrhj** [openimsdk/open-im-sdk-reactnative#36]
### OpenIM Server Version

3.8.0

### Operating System and CPU Architecture

Linux (AMD)

### Deployment Method

Source Code Deployment

### Bug Description and Steps to Reproduce

open-im-sdk-rn version is 3.8.1-rc.1

crash message:
```
Error when sending event: onConnecting with body: (null). RCTCallableJSModules is not set. This is probably because you've explicitly synthesized the RCTCallableJSModules in OpenIMSDKRN, even though it's inherited from RCTEventEmitter.
```

**Comment by Bloomingg** [comment]
Is it on iOS? What is the react-native version number?

**Comment by ahjsrhj** [comment]
> Is it on iOS? What is the react-native version number?

Yes, the react-native version number is 0.73.5
I downgraded the open-im-sdk-rn version to 3.8.1-rc.0, and it works fine now.

**Comment by ahjsrhj** [comment]
sorry I update to 3.8.1-rc.1 and clean build again it can work now
