### ISSUE TITLE
[BUG] params type is error

### ISSUE THREAD

**Issue by daxingyun** [openimsdk/open-im-sdk-reactnative#39]
### OpenIM Server Version

3.8.0

### Operating System and CPU Architecture

Linux (AMD)

### Deployment Method

Source Code Deployment

### Bug Description and Steps to Reproduce

createVideoMessageFromFullPath: (
    params: string,
    operationID: string
  ) => Promise<MessageItem>;
  createSoundMessageFromFullPath: (
    params: string,
    operationID: string
  ) => Promise<MessageItem>;
  createFileMessageFromFullPath: (
    params: string,
    operationID: string
  ) => Promise<MessageItem>;
这几个接口的参数params的类型是错误的，比如createSoundMessageFromFullPath的参数params不应该是String类型，而应该是一个对象，传入String类型会崩溃。

### Screenshots Link

createVideoMessageFromFullPath: (
    params: string,
    operationID: string
  ) => Promise<MessageItem>;
  createSoundMessageFromFullPath: (
    params: string,
    operationID: string
  ) => Promise<MessageItem>;
  createFileMessageFromFullPath: (
    params: string,
    operationID: string
  ) => Promise<MessageItem>;

**Comment by lgz5689** [comment]
Ok, this will be fixed in version 3.8.1
