### ISSUE TITLE
android 下面maven地址需要加自定义的 121.37.25.71那个地址

### ISSUE THREAD

**Issue by TQCasey** [OpenIMSDK/Open-IM-SDK-ReactNative#4]
如题，直接run是通不过的，需要改下 app 的 build.gradle

        maven {
            allowInsecureProtocol = true
            url 'http://121.37.25.71:8081/repository/maven-releases'
        }

**Comment by Bloomingg** [comment]
readme有写哦

**Comment by TQCasey** [comment]
哦，好的，我没看到，不好意思我冒失了
