### ISSUE TITLE
[BUG]  Could not get resource 'https://open-im-online.rentsoft.cn:51000/repository/maven2/io/openim/core-sdk/3.8.1/core-sdk-3.8.1.pom'

### ISSUE THREAD

**Issue by wuchaoqun817** [openimsdk/open-im-sdk-reactnative#44]
### OpenIM Server Version

3.8.1

### Operating System and CPU Architecture

Windows (AMD)

### Deployment Method

Docker Deployment

### Bug Description and Steps to Reproduce

 Could not get resource 'https://open-im-online.rentsoft.cn:51000/repository/maven2/io/openim/core-sdk/3.8.1/core-sdk-3.8.1.pom'

### Screenshots Link

 Could not get resource 'https://open-im-online.rentsoft.cn:51000/repository/maven2/io/openim/core-sdk/3.8.1/core-sdk-3.8.1.pom'

**Comment by lgz5689** [comment]
My visit here is normal, you can try again later or consider changing the agent.
