### ISSUE TITLE
[BUG] OpenIMSDKRN.getGroupMemberList not return group owner information, only group members

### ISSUE THREAD

**Issue by 15975019972** [openimsdk/open-im-sdk-reactnative#45]
### OpenIM Server Version

3.7.1

### Operating System and CPU Architecture

Linux (AMD)

### Deployment Method

Source Code Deployment

### Bug Description and Steps to Reproduce

[BUG] OpenIMSDKRN.getGroupMemberList 调用没有返回群主信息，只有群成员；修改filter也没有返回相关的筛选项；
参数
  const params = {
            groupID,
            filter: "ALL",
            offset: 1,
            count: 500,
        };

**Comment by 15975019972** [comment]
所有的filter选项都只返回一个

**Comment by lgz5689** [comment]
The filter argument is of type number and passes 0 to return all members
