### ISSUE TITLE
[BUG] ios onRecvNewMessages fail

### ISSUE THREAD

**Issue by OrrinHatch** [openimsdk/open-im-sdk-reactnative#47]
### OpenIM Server Version

3.8.0

### Operating System and CPU Architecture

Linux (AMD)

### Deployment Method

Docker Deployment

### Bug Description and Steps to Reproduce

The message reception works fine on Android, but iOS is unable to receive messages.

**Comment by lgz5689** [comment]
Please update the sdk and server to the latest. If the problem still exists, please collect detailed logs so that we can better locate the problem.

**Comment by OrrinHatch** [comment]
SDK version "open-im-sdk-rn": "3.8.1-rc.1",

**Comment by lgz5689** [comment]
`onRecvNewMessages` is not triggered when a message is received, but is it possible to query messages via other apis?

**Comment by OrrinHatch** [comment]
i don't understand object-c development, can not fix it
please fix it

**Comment by OrrinHatch** [comment]
When I use onRecvNewMessage on IOS, I can successfully receive new messages

**Comment by lgz5689** [comment]
Thank you. According to your description, we should already know where the problem is and we will fix it as soon as possible

**Comment by lgz5689** [comment]
> When I use onRecvNewMessage on IOS, I can successfully receive new messages

Thank you. According to your description, we should already know where the problem is and we will fix it as soon as possible

**Comment by lgz5689** [comment]
You can try using the content of this pr to confirm if the fix has been completed. However, it is expected that `onRecvNewMessages` will also be deprecated in the next version, please note
