### ISSUE TITLE
[BUG] ios onConnecting fail

### ISSUE THREAD

**Issue by OrrinHatch** [openimsdk/open-im-sdk-reactnative#48]
### OpenIM Server Version

3.8.0

### Operating System and CPU Architecture

Linux (AMD)

### Deployment Method

Docker Deployment

### Bug Description and Steps to Reproduce

<img width="795" alt="截屏2024-10-30 17 45 12" src="https://github.com/user-attachments/assets/6070919c-12bb-4487-bc02-72e0a3ce582d">

**Comment by lgz5689** [comment]
Is this the only event that can do this? We don't seem to have this error here
