### ISSUE TITLE
[BUG] react-native0.58.0 OpenImSdkRnModule  createTextMessage Open_im_sdk.createTextMessage(operationID, textMsg) return ""

### ISSUE THREAD

**Issue by ws614054446** [openimsdk/open-im-sdk-reactnative#56]
### OpenIM Server Version

3.8.2

### Operating System and CPU Architecture

Linux (AMD)

### Deployment Method

Source Code Deployment

### Bug Description and Steps to Reproduce

react-native版本是0.58.0
在调用OpenIMSDKRN.createTextMessage时，桥接文件OpenImSdkRnModule 里的createTextMessage 方法里调用的Open_im_sdk.createTextMessage(operationID, textMsg) 返回空。
OpenIMSDKRN.initSDK和OpenIMSDKRN.login已返回成功。
是react-native版本导致的吗，还是其他原因引起的。
react-native0.58版本openim该用哪个版本的SDK好

**Comment by lgz5689** [comment]
`createTextMessage` is generated locally, you can use logcat to collect logs from `sdk-core`, it should have an error saying why can't it execute correctly

**Comment by ws614054446** [comment]
ws登录不成功导致的
