### ISSUE TITLE
[BUG] Docker deployment configured nginx domain to send images will fail

### ISSUE THREAD

**Issue by youfak** [openimsdk/open-im-sdk-reactnative#57]
### OpenIM Server Version

3.8.1

### Operating System and CPU Architecture

Linux (AMD)

### Deployment Method

Docker Deployment

### Bug Description and Steps to Reproduce

Error: error *errors.withStack not implement CodeError: api /object/part_limit json.Unmarshal("<html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body>\r\n<center><h1>502 Bad Gateway</h1></center>\r\n<hr><center>nginx/1.23.3</center>\r\n</body>\r\n</html>\r\n", *network.ApiResponse) failed invalid character '<' looking for beginning of value: 10006 Internal SDK error]

Previously, it was successfully sent using an IP address, but now it can be accessed correctly through the domain name. However, new images cannot be sent

**Comment by lgz5689** [comment]
Configure the server configuration and nginx correctly according to the official stable
