### ISSUE TITLE
[BUG] open-im-sdk-rn@3.8.2 does not have the platformID field.

### ISSUE THREAD

**Issue by ahjsrhj** [openimsdk/open-im-sdk-reactnative#59]
### OpenIM Server Version

3.8.0

### Operating System and CPU Architecture

Linux (AMD)

### Deployment Method

Source Code Deployment

### Bug Description and Steps to Reproduce

The parameter type of method initSDK is
```
export type InitOptions = {
  wsAddr: string;
  apiAddr: string;
  dataDir: string;
  logLevel: LogLevel;
  isLogStandardOutput: boolean;
};
```
Is platformID no longer needed? Why is there still one in the document?

**Comment by ahjsrhj** [comment]
And now the maven repository is also inaccessible
```
      > Could not resolve io.openim:core-sdk:3.8.2.
         > Could not get resource 'https://open-im-online.rentsoft.cn:51000/repository/maven2/io/openim/core-sdk/3.8.2/core-sdk-3.8.2.pom'.
            > Could not HEAD 'https://open-im-online.rentsoft.cn:51000/repository/maven2/io/openim/core-sdk/3.8.2/core-sdk-3.8.2.pom'.
```
I'm sure it's not a problem with my network, because I've tried pulling from different networks and through a vps server, with the same failure

**Comment by lgz5689** [comment]
Now in Android and iOS environments, the current platformID is used by default, and no pass is needed.

**Comment by lgz5689** [comment]
You can try fetching the latest code, which uses mavenCentral as a remote repository

**Comment by ahjsrhj** [comment]
> You can try fetching the latest code, which uses mavenCentral as a remote repository


I saw in the document that the link address is still https://open-im-online.rentsoft.cn:51000/repository/maven2, and the version number I am using is the latest version 3.8.2. Do you mean there is more New version?

**Comment by lgz5689** [comment]
Looking at the latest code No additional maven configuration is required

**Comment by ahjsrhj** [comment]
OK, I will try to update again later, thanks for the reply
