### ISSUE TITLE
Maven link

### ISSUE THREAD

**Issue by blueOMG** [openimsdk/open-im-sdk-reactnative#9]
### What happened?

maven无法下载

### What did you expect to happen?

maven无法下载

### How can we reproduce it (as minimally and precisely as possible)?

maven无法下载

### version

<details>
```console
$ {name} version
# paste output here
```
</details>

### Cloud provider

<details>
</details>

### OS version

<details>
```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here
# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```
</details>

### Install tools

<details>
</details>

**Comment by AndrewZuo01** [comment]
Do you have detailed info for this problem?
